### PR TITLE
Network dropdown

### PR DESCRIPTION
**Pull request by toniengelhardt**
Replacement for https://github.com/toniengelhardt/m3tadata/pull/31.

### CODE REVIEW

**Comment by toniengelhardt** [comment]
@RyanPaulGannon take a look at this one. 

Actual selection of the network is not working yet, but the dropdown is. Orientation of the dropdowns can now be selected via prop `orientation` left or right.

**Comment by RyanPaulGannon** [comment]
This looks good. At the moment it's not visible though? I've played around with it and seen the dropdown working as you say. Even though I can see that the `chainId === 1` and `connected` it doesn't show the ETH Mainnet. I can sort of grasp how it works, this is much better than my hardcoded attempt, haha.

Thanks for closing too!

**Comment by toniengelhardt** [comment]
Ah, maybe an issue with WalletConnect. With MetaMask it seems to work for me when I test mobile viewport on Chrome desktop. Will take a look.

**Comment by RyanPaulGannon** [comment]
I've only tried with Brave and Safari, but not showing on either (mobile or desktop). That's with using all three of the options. 
Screenshot 2022-12-30 at 14 15 59
Screenshot 2022-12-30 at 14 15 37

**Comment by toniengelhardt** [comment]
Looking at it rn, I think it's probably bc the network name is homestead and not ethereum.

**Comment by toniengelhardt** [comment]
Should work now, I renamed ethereum to homestead and polygon to matic in networks.

One problem that still persists is that the wallet connection gets lost when you connect via WalletConnect and reload the page.

**Comment by RyanPaulGannon** [comment]
Looking good!

**Pull request merged**
