### PR TITLE
feat: matic gasPrice

### PR DESCRIPTION
**Pull request by RyanPaulGannon**
So, bit of a test this I think. Again, using the Alchemy RPC. 

It grabs the Polygon `gasPrice` as I was trying to do. However, some questions:

1. Would we need to create something similar for each 'chain'?
2. I've included the `updateMaticGasPrice()` in to the store which I presume is best practice. Is this something we will have to split up if indeed the first questions answer is 'yes'? Or could we group the actions do you think?

Tried to keep this small as I have the feeling it opens up something which could grow quite wildly, haha?

### CODE REVIEW

**Comment by toniengelhardt** [comment]
Looks good!

I'm not sure, if the provider could be reused it would be nice, but it looks like the data is only available in two different providers? If that is the case I think it is good for now, we can optimize later. The only thing we have to keep in mind is the API request limit, but I think the solution for that would be to move these things into server functions and cache the results that are the same for all users. But that's for later.

Btw the checks should be working now and there is a type error, is that legit?

**Comment by RyanPaulGannon** [comment]
Maybe, unless my understanding is a little off? We've an RPC Provider now from both ETH & Polygon mainnet (rightly or wrongly?), we would need one for say, Optimism? Unless we can even use just the one provider and access the other Layer's off the ETH mainnet? Something I'll have a look in to.

Good suggestion with the function, limit is 301.0m, we've currently used 1.1.

Yes, TypeError is my bad! Will fix. Funny VS Code didn't catch that, TS normally loves shouting at me haha!

**Comment by RyanPaulGannon** [comment]
Not 100% certain with this, passes the test. But the Type needs addressing. 

Maybe goes back to not needing to access `maticProvider` directly, maybe we can access it through `defaultProvider`?

Screenshot 2022-12-30 at 19 47 58

**Comment by RyanPaulGannon** [comment]
This is much better!

So, as per the ethers link https://docs.ethers.org/v5/api/providers/api-providers/#AlchemyProvider, we can use the `defaultProvider` and pass in an argument of one of their supported networks.

I've changed: 

```js
actions: {
    async updateBlocknumber() {
      try {
        const defaultProvider = await useDefaultProvider('homestead') <-- CHANGED
        this.homestead.blocknumber = await defaultProvider.getBlockNumber()
        this.homestead.status = 'connected'
      }
      catch {
        this.homestead.status = 'error'
      }
      return Promise.resolve()
    },
    async updateGasPrice() {
      try {
        const defaultProvider = await useDefaultProvider('homestead') <-- CHANGED
        const gp = await defaultProvider.getGasPrice()
        this.homestead.gasPrice = Math.round(+ethersUtils.formatUnits(gp, 'gwei'))
      }
      catch { }
      return Promise.resolve()
    },
    async updateMaticGasPrice() {
      try {
        const defaultProvider = await useDefaultProvider('matic') <-- CHANGED
        const gp = await defaultProvider.getGasPrice()
        this.matic.gasPrice = Math.round(+ethersUtils.formatUnits(gp, 'gwei'))
        this.matic.status = 'connected'
      }
      catch { }
      return Promise.resolve()
    },
```
which initially gave the TypeErrors (apologies, should have ran the checks before pushing, realised afterwards!).

Also updated the argument `rabbithole.ts` and added the Type ...

`export const useDefaultProvider = async (network: NetworkName) => {`

**Comment by toniengelhardt** [comment]
Nice, great work! 

No probs, the idea of the checks is to catch these things. With the GitHub Actions we do not need to build, etc. the stuff locally before pushing, more efficient IMO. Btw, the type errors should show up in realtime in your editor. If you use VS Code in [takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) the IDE should show the same errors as the tests.

I'll merge this but will move the Matic gas price check into `updateGasPrice()`. I think we don't need to have a function for each of those.

**Comment by toniengelhardt** [comment]
**Update:** Just tested the implementation and unfortunately it doesn't work this way. If you look at the `useDefaultProvider` composable, it only instantiates the provider once if it doesn't exist and then reuses it the next time it  is called for efficiency, meaning if you call it first with 'homestead' argument and then with 'matic' argument it will in both cases return the 'homestead' provider. So, for now, unfortunately, we need one default provider per network.

But don't worry about it, I'll push a fix for it.

**Comment by RyanPaulGannon** [comment]
It does? I'm getting two different Gwei prices, that both seem to match the current prices when checking them against the online price.

However, I have broke the `PriceFeed`, although now I've currently got the `ETH` price working, will await you commit before pushing (if pushing at all).

**Comment by toniengelhardt** [comment]
Really? That's weird, for me it showed either the ETH or MATIC price for both. Anyway, I just pushed a fix. Also shows the correct Network info on the top now depending on which Network is selected.

**Comment by RyanPaulGannon** [comment]
Looks good!

**Pull request merged**
