### PR TITLE
feat: panel for price feeds

### PR DESCRIPTION
**Pull request by RyanPaulGannon**
Maybe closes: #5?

Started by adding an ETH/USD price feed using Chainlink Data Feeds.

I played around with it located at in the Action Bar, but then decided to throw it in to one of the panels as there are a number of potential price feeds and maybe would look better in an overflow?

The RPC_URL is a test one I created on Alchemy in the meantime.

Is this the sort of thing you are looking for regarding #5?

### CODE REVIEW

**Comment by toniengelhardt** [comment]
Amazing! I'll take a look 🙏🏽

**Comment by toniengelhardt** [comment]
@RyanPaulGannon I merged it ✌🏽 Just did some renaming of the things.

Amazing to use ChainLink for this! From what I understand, for now we can access the contracts for free, but might be required to pay $LINK in the future to get data...

Reg. https://github.com/toniengelhardt/m3tadata/issues/5, yes, but that's just the easy part. The tricky one will be to get the historical data for each transaction to calculate performance in USD/EUR/...

Good work 🙏🏽 🙏🏽 🙏🏽

**Comment by toniengelhardt** [comment]
The name of the component is always camel case of folder structure plus file name, e.g. 

```bash
/components/transaction/item/Send.vue = <TransactionItemSend.vue />
```

It's really cool! It's also smart enough to omit duplication when the file name is the same as the folder name, e.g.

```bash
/components/transaction/item/Item.vue = <TransactionItem.vue />
```

**Comment by RyanPaulGannon** [comment]
Ahh, gotcha, appreciate that my friend! 🙏

**Comment by toniengelhardt** [comment]
No probs, I made this project exactly to play and learn from each other 😉

**Pull request merged**
